# Generated by Django 5.0.6 on 2024-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
