services:
  rubens_blog:
    restart: always
    build: ./rubens_blog
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./:/app
      - /var/www/static/:/var/www/static/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file: .env_production
    environment:
      DEBUG: 'true'
    # command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config gunicorn_config.py rubens_blog.wsgi"
    command: /usr/local/bin/gunicorn --config gunicorn_config.py rubens_blog.wsgi

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/www/static/:/srv/www/static/
      - ./production/nginx.conf/:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - rubens_blog

  postgres:
    restart: always
    image: postgres:15.6
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - .env_production


volumes:
  pgdata:
