services:
  rubens_blog:
    restart: always
    build: ./rubens_blog
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    volumes:
      - ./rubens_blog/:/app
      - /srv/www/static/:/srv/www/static/
      - /etc/letsencrypt/live/rubenvoss.de/fullchain.pem:/etc/letsencrypt/live/rubenvoss.de/fullchain.pem
      - /etc/letsencrypt/live/rubenvoss.de/privkey.pem:/etc/letsencrypt/live/rubenvoss.de/privkey.pem
    env_file: .env_production
    environment:
      DEBUG: 'true'
    # command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config gunicorn_config.py rubens_blog.wsgi"
    command: /usr/local/bin/gunicorn --config gunicorn_config.py rubens_blog.wsgi

  postgres:
    container_name: postgres
    restart: always
    image: postgres:15.6
    shm_size: 128mb
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - .env_production


volumes:
  pgdata:
