#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
    ALTER DATABASE $POSTGRES_DB OWNER TO $POSTGRES_USER;
    ALTER ROLE $POSTGRES_USER SET client_encoding TO 'utf8';
    ALTER ROLE $POSTGRES_USER SET default_transaction_isolation TO 'read committed';
    ALTER ROLE $POSTGRES_USER SET timezone TO 'CET';
    \connect $POSTGRES_DB
    CREATE SCHEMA $POSTGRES_SCHEMA AUTHORIZATION $POSTGRES_USER;
EOSQL