# Generated by Django 5.0.6 on 2024-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigationsettings",
            name="mastodon_url",
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="twitter_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn"),
        ),
    ]
