# Generated by Django 5.0.6 on 2024-05-07 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_navigationsettings_mastodon_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="navigationsettings",
            old_name="twitter_url",
            new_name="linkedin_url",
        ),
    ]
